hw_project/hw_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("quotes.urls")),
    # path("users/", include("users.urls"))
]

hw_project/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetCompleteView, PasswordResetDoneView, PasswordResetConfirmView

from .forms import LoginForm
from .views import RegisterView

app_name = 'users'


urlpatterns = [
    path('users/registration/', RegisterView.as_view(), name='signup'),
    path('login/',
         LoginView.as_view(template_name='users/login.html', form_class=LoginForm, redirect_authenticated_user=True),
         name='signin'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html', ), name='logout'),
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

hw_project/users/models.py
from django.db import models

# Create your models here.

hw_project/users/forms.py
from django import forms
from django.forms import ModelForm, CharField, TextInput, EmailField, EmailInput, PasswordInput
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class RegisterForm(UserCreationForm):
    username = CharField(max_length=16, required=True,
                         widget=TextInput(attrs={"class": "form-control"}))
    email = CharField(max_length=16, required=True,
                      widget=EmailInput(attrs={"class": "form-control"}))
    password1 = CharField(max_length=16, min_length=6, required=True,
                          widget=PasswordInput(attrs={"class": "form-control"}))
    password2 = CharField(max_length=16, min_length=6, required=True,
                          widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=50,
                               required=True,
                               widget=forms.TextInput(attrs={"class": "form-control"}))

    password = forms.CharField(max_length=20,
                               required=True,
                               widget=forms.PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ['username', 'password']

hw_project/users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from .forms import RegisterForm, LoginForm


# Create your views here.


class RegisterView(View):
    template_name = 'users/register.html'
    form_class = RegisterForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to='quotes:main')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, {"form": self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='users:signin')

        return render(request, self.template_name, {'form': form})


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'


def signup(request):
    if request.user.is_authenticated:
        return redirect(to='quotes:root')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:root')
        else:
            return render(request, 'users/signup.html', context={'form': form})

    return render(request, 'users/signup.html', context={'form': RegisterForm()})


def login_user(request):
    if request.user.is_authenticated:
        return redirect(to='quotes:root')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='quotes:root')

    return render(request, 'users/login.html', context={'form': LoginForm})


@login_required
def logout_user(request):
    logout(request)
    return redirect(to='quotes:root')

hw_project/users/templates/users/login.html
{% extends "quotes/base.html" %}

{% block content %}

<div class="container mt-3">
    <h2 class="mb-2">User Login</h2>


</div>
{% endif %}
{%if form.errors and form.non_field_errors %}
<span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
{% endif %}
<form method='post'>
    {% csrf_token %}
    <div class="mb-2">
        <label class="form-label">Username
            {{ form.username }}
        </label>
        <span>{{form.errors.username}}</span>
    </div>

    <div class="mb-2">
        <label class="form-label">Password
            {{ form.password }}
        </label>
        <span>{{form.errors.password}}</span>
    </div>

    <div class="mb-2">
        <button type="submit" class="btn btn-primary">Send</button>
        <button type="reset" class="btn btn-primary">Reset</button>
    </div>
    <div class="small text-center">
            <a href="{% url "users:password_reset" %}" class="text-center"><i>Forgot Password?</i></a>
       </div>
</form>
</div>

{% endblock %}

hw_project/users/templates/users/logout.html
{% extends "quotes/base.html" %}
{% block content %}
 <div class="container mt-3">
    <h2 class="mb-3">logged out!</h2>
 <div>
{% endblock %}

hw_project/users/templates/users/password_reset.html
<{% extends "quotes/base.html" %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

hw_project/users/templates/users/password_reset_complete.html
{% extends "quotes/base.html" %}

{% block content %}

    <h2>Password reset complete!</h2>

{% endblock %}

hw_project/users/templates/users/password_reset_confirm.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

hw_project/users/templates/users/password_reset_done.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

hw_project/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

hw_project/users/templates/users/register.html
{% extends "quotes/base.html" %}
{% block content %}

<div class="container">
    <h2>Registration User</h2>
    {% if form.errors and form.non_field_errors %}
    <span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username
                {{ form.username }}
            </label>
            <span>{{form.errors.username}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Email
                {{ form.email }}
            </label>
            <span>{{form.errors.email}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Password
                {{ form.password1 }}
            </label>
            <span>{{form.errors.password1}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Repeat Password
                {{ form.password2 }}
            </label>
            <span>{{form.errors.password2}}</span>
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary">Send</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
    </form>

</div>

{% endblock %}