hw_project/hw_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("quotes.urls")),
    # path("users/", include("users.urls"))
]

hw_project/quotes/urls.py
from django.urls import path

from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.main, name="root"),
    path("<int:page>", views.main, name="root_paginate"),
    path('author/<str:id_>', views.author, name='author'),
    path('tag/<str:tag_name>/', views.find_tag, name='find_tag'),
    path('add_author/', views.add_author, name='add_author'),
    path('add_quote/', views.add_quote, name='add_quote')
]

hw_project/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetCompleteView, PasswordResetDoneView, PasswordResetConfirmView

from .forms import LoginForm
from .views import RegisterView

app_name = 'users'


urlpatterns = [
    path('users/registration/', RegisterView.as_view(), name='signup'),
    path('login/',
         LoginView.as_view(template_name='users/login.html', form_class=LoginForm, redirect_authenticated_user=True),
         name='signin'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html', ), name='logout'),
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

hw_project/quotes/models.py
from django.db import models


class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField(default='Default description')
    created_at = models.DateTimeField(auto_now_add=True)


class Tag(models.Model):
    name = models.CharField(max_length=30, null=False, unique=True)


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)

hw_project/quotes/forms.py
from django.forms import ModelForm, CharField, TextInput, Textarea
from .models import Author, Quote, Tag



class AddAuthor(ModelForm):
    fullname = CharField(max_length=40, min_length=5, widget=TextInput(attrs={'class': 'form-control'}))
    born_date = CharField(max_length=25, min_length=12, widget=TextInput(attrs={'class': 'form-control'}))
    born_location = CharField(max_length=150, min_length=12, widget=TextInput(attrs={'class': 'form-control'}))
    description = CharField(widget=Textarea(attrs={'class': 'form-control', 'size': 50}))

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']


class AddForm(ModelForm):
    author = CharField(min_length=5, max_length=150, required=True, widget=TextInput(attrs={'class': 'form-control'}))
    quote = CharField(min_length=5, required=True, widget=Textarea(attrs={'class': 'form-control'}))
    tags = CharField(required=False, widget=TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Quote
        fields = ['quote', 'tags', 'author']

hw_project/quotes/views.py
from bson import ObjectId
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

from django.shortcuts import render, redirect

from .utils import get_mongodb
from .models import Author, Quote, Tag
from .forms import AddAuthor, AddForm


def main(request, page=1):
    db = get_mongodb()
    quotes = db.quotes.find()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})


def author(request, id_):
    db = get_mongodb()
    author_info = db.authors.find_one({'_id': ObjectId(id_)})
    return render(request, 'quotes/author.html', context={'author': author_info})


def find_tag(request, tag_name):
    tag = Tag.objects.get(name=tag_name)
    quotes = Quote.objects.filter(tags=tag)
    context = {
        'tag': tag,
        'quotes': quotes
    }
    return render(request, 'quotes/tags.html', context)


@login_required
def add_author(request):
    if request.method == 'POST':
        form = AddAuthor(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:root')
        else:
            return render(request, 'quotes/add_author.html', context={'form': form})

    return render(request, 'quotes/add_author.html', context={'form': AddAuthor()})


@login_required
def add_quote(request):
    if request.method == 'POST':
        form = AddForm(request.POST)
        if form.is_valid():
            new_quote = form.save(commit=False)
            new_quote.user = request.user
            new_quote.save()
            return redirect(to='quotes:root')
        else:
            return render(request, 'quotes/add_quote.html', context={'form': form})

    return render(request, 'quotes/add_quote.html', context={'form': AddAuthor()})

hw_project/quotes/templates/quotes/add_author.html
{%extends 'quotes/base.html' %}

{% block content %}

<div class="container mt-3">
    <h3>Add New Author</h3>
    {%if form.errors and form.non_field_errors %}
    <span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
    {% endif %}

    <form action="{% url 'quotes:add_author' %}" method='post' enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mt-3">
            <label class="form-label">Author name
                {{ form.fullname }}
            </label>
            <span>{{form.errors.fullname}}</span>
        </div>

        <div class="mt-3">
            <label class="form-label">Born date
                {{ form.born_date }}
            </label>
            <span>{{form.errors.born_date}}</span>
        </div>

        <div class="mt-3">
            <label class="form-label">Born location
                {{ form.born_location }}
            </label>
            <span>{{form.errors.born_location}}</span>
        </div>

        <div class="mt-3">
            <label class="form-label">Biography
                {{ form.description }}
            </label>
            <span>{{form.errors.description}}</span>
        </div>

        <div class="mt-3">
            <button type="submit" class="btn btn-primary">Send</button>
            <button type="reset" class="btn btn-primary">Reset</button>
        </div>

    </form>
</div>
{% endblock %}

hw_project/quotes/templates/quotes/add_quote.html
{%extends 'quotes/base.html' %}

{% block content %}

 <div class="container mt-3">
    <h1>Add New quote</h1>
    {%if form.errors and form.non_field_errors %}
    <span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
    {% endif %}
    <form action="{% url 'quotes:add_quote' %}" method='post' enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
          <label class="form-label">Author name
          {{ form.author }}
          </label>
          <span>{{form.errors.author}}</span>
        </div>
        <div class="mb-3">
          <label  class="form-label">Quote
          {{ form.quote }}
          </label>
          <span>{{form.errors.quote}}</span>
        </div>
        <div class="mb-3">
          <label  class="form-label">Tags (separate by comma)
          {{ form.tags }}
          </label>
          <span>{{form.errors.tags}}</span>
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary">Send</button>
            <button type="reset" class="btn btn-primary">Reset</button>
        </div>
    </form>
 </div>
{% endblock %}

hw_project/quotes/templates/quotes/author.html
{% extends 'quotes/base.html' %}
{% block content %}

{% if author %}
    <h1>{{ author.fullname }}</h1>
    <p><strong>Date of birth:</strong> {{ author.born_date }} {{ author.born_location }}</p>
    <p><strong>Description:</strong> {{ author.description }}</p>
{% else %}
    <p>Author not found.</p>
{% endif %}

{% endblock %}

hw_project/quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>Homework</title>
</head>
<body>
<div class="container">
    <div class="row header-box pt-3 mb-3">
        <div class="col-md-8">
            <h1>
                <a href="/" style="text-decoration: none">Quotes to Scrape</a>
            </h1>
        </div>
            <div class="col-md-4">
                <div class="col-md-4">
                {% if user.is_authenticated %}
                <p>
                    <a href="{% url 'quotes:add_quote' %}" class="btn btn-success">Add quote</a>
                    <a href="{% url 'quotes:add_author' %}" class="btn btn-success">Add author</a>
                    <a href="{% url 'users:logout' %}" class="btn btn-primary">Logout</a>
                </p>
                {% else %}
                <p>
                    <a href="{% url 'users:signup' %}" class="btn btn-primary">Sign Up</a>
                    <a href="{% url 'users:login' %}" class="btn btn-primary">Sign In</a>
                </p>
                {% endif %}
        </div>

    </div>


    {% block content %} {% endblock %}

</div>
</body>
</html>

hw_project/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}
{% block content %}

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">
            {{quote.quote}}
        </span>
            <span>by <small class="author" itemprop="author">{{quote.author|author}}</small>
        <a href="/author/{{quote.author}}">(about)</a>
        </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags %}
                <a class="tag" href="/tag/{{tag}}">{{tag}}</a>
                {% endfor %}
            </div>
        </div>

        {% endfor %}
        <nav>
            <ul class="pager">
                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                       href="{% if quotes.has_previous %} {% url 'quotes:root_paginate'  quotes.previous_page_number %} {% else %} # {% endif %}">
                        <span aria-hidden="true">←</span> Previous
                    </a>
                </li>

                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}"
                       href="{% if quotes.has_next %} {% url 'quotes:root_paginate'  quotes.next_page_number %} {% else %} # {% endif %}"
                            >Next <span aria-hidden="true">→</span>
                    </a>
                </li>

            </ul>
        </nav>
    </div>

</div>

{% endblock %}

hw_project/quotes/templates/quotes/tags.html
{% extends 'quotes/base.html' %}
{% block content %}

<h3>Viewing tag: <a href="/tag/{{ tag_name }}" style="text-decoration: none;">{{ tag_name }}</a></h3>
<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">{{ quote.quote }}</span>
            <span>by <small class="author" itemprop="author">{{ quote.author.fullname }}</small>
                <a href="{% url 'quotes:author' quote.author.id %}" style="text-decoration: none;">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                <a class="tag" style="text-decoration: none;" href="/tag/{{ tag.name }}">{{ tag.name }}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}